name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, 1.45]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
    - name: W/A rust-lang/cargo#10303
      if: matrix.rust == '1.45'
      run: cargo update
      env:
          CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    - name: Build
      run: cargo build --all-targets --all-features
    - name: Test
      run: cargo test --all-features

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
    - name: Run rustfmt
      run: cargo fmt --all -- --check
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
